---
- name: Install Stuff
  hosts: tag_Name_mrmeseeks
  remote_user: centos
  become: true
  vars:
    - region: us-east-2
    - project_name: meseeks
    - vpcidr: 10.251.0.0/16
    - subnetcidr: 10.251.1.0/24

  roles:
    - common
    - mr-centos
