---
- name: download tower installer
  unarchive:
    src: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
    dest: /tmp/
    mode: 0640

- name: extract installer
  unarchive:
    src: /tmp/ansible-tower-setup-latest.tar.gz
    dest: /tmp/

- name: template inventory file
  template:
    src: inventory
    dest: /tmp/ansible-tower-setup-{{ towerversion }}/inventory

- name: run the tower installer
  shell: ./setup.sh
    chdir: /tmp/ansible-tower-setup-{{ towerversion }}

- name: copy ansible hosts file
  copy:
    src: hosts
    dest: /etc/ansible/hosts

- name: Post license key
  uri:
    url: https://localhost/api/v1/config/
    method: POST
    user: admin
    password: "{{ towerpass }}"
    body: "{{ lookup('file','tower_license.json') }}"
    body_format: json
    validate_certs: False
  when: license is undefined

# - name: import inventory to Tower demo inventory
#   shell: tower-manage inventory_import --source=/etc/ansible/hosts --inventory-id=1
#   when: license is undefined
